// <auto-generated />
namespace DbLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InstanceUsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstanceUsage));
        
        string IMigrationMetadata.Id
        {
            get { return "201307031313020_InstanceUsage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
