// <auto-generated />
namespace DbLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Role_UserRole_ComponentRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_UserRole_ComponentRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201307080916358_Role_UserRole_ComponentRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
