// <auto-generated />
namespace DbLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DataLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201307042225334_DataLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
